const data = {
  products: [
    {
      _id: "1",
      name: "Nike slim shirt",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "2",
      name: "Adidas slim shirt",
      category: "shirt",
      image: "/images/p2.jpg",
      price: 135,
      brand: "Adidas",
      rating: 4.8,
      numReviews: 12,
      description: "high quality products",
    },
    {
      _id: "3",
      name: "Top slim shirt",
      category: "shirt",
      image: "/images/p3.jpg",
      price: 560,
      brand: "Top",
      rating: 4.5,
      numReviews: 20,
      description: "high quality products",
    },
    {
      _id: "4",
      name: "Puma slim pants",
      category: "pants",
      image: "/images/p4.jpg",
      price: 344,
      brand: "Puma",
      rating: 5,
      numReviews: 12,
      description: "high quality products",
    },
    {
      _id: "5",
      name: "adidas slim pants",
      category: "pants",
      image: "/images/p5.jpg",
      price: 150,
      brand: "Adidas",
      rating: 4.4,
      numReviews: 32,
      description: "high quality products",
    },
    {
      _id: "6",
      name: "Infinity slim pants",
      category: "pants",
      image: "/images/p6.jpg",
      price: 160,
      brand: "infinity",
      rating: 5,
      numReviews: 34,
      description: "high quality products",
    },
  ],
};

export default data;
